import type { NextPage } from 'next';
import { Input } from '../components/input';

import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Poketype!</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Input />
		</div>
	);
};

export default Home;
