import type { NextPage } from 'next'
import Head from 'next/head'
import { Input } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       
        <Input placeholder='Basic usage' mt='5'/>
        <div className='main'> Hello</div>
        </main>
    </div>
  )
}

export default Home
